### ISSUE TITLE
benchbark codebase release timeline

### ISSUE THREAD

**Issue by ShockleysxX** [noewangjy/csprd_dataset#3]
Hi, @noewangjy, this is a very interesting financial data set, when will the relevant baseline code be released? Thank you.

**Comment by liuxiaocs7** [comment]
+1

**Comment by noewangjy** [comment]
Sorry for the late update, I have been occupied by the graduation affairs. The code and scripts have been updated now. If you have any questions or find any bugs, please start a new issue or send me an email. Thanks for you patience and attention :-)

**Comment by liuxiaocs7** [comment]
Hi, @noewangjy, i see, thank you for your efforts in updating so quickly. Could you please provide the environment file `requirements.txt` please?

**Comment by noewangjy** [comment]
> Hi, @noewangjy, i see, thank you for your efforts in updating so quickly. Could you please provide the environment file `requirements.txt` please?

The `requirements.txt` has been uploaded for you convenience.

However, the original environment for experiments are no longer available to me. Please note that this `requirements.txt` is collected according to a local environment created at near time, some packages may not be in the same version, but it might work to run the code. If not, please adjust the versions to an order or newer version.
